#!/bin/sh
VERSION=`../utils/cutver.sh libxml_xmlwin32version.inc`
LIBNAME=libxml2
PACKAGE=$LIBNAME-pas
RELEASENAME=$PACKAGE-$VERSION-src
TAG="`echo $LIBNAME\_$VERSION | tr [:lower:] [:upper:] | sed 's/\./_/g'`"
MYTMP=./$TAG.tmp
CVSROOT=:pserver:anonymous@cvs.sourceforge.net:/cvsroot/libxml2-pas


echo "Extracting $LIBNAME-pas from CVS tag $TAG ..."
rm -rf $MYTMP
cvs -z4 -d $CVSROOT export -r $TAG -d $MYTMP .

ARCHIVEFILE=$RELEASENAME.tgz
echo "Preparing archive $ARCHIVEFILE ..."
rm -f $ARCHIVEFILE
cd $MYTMP
tar -zcf ../$ARCHIVEFILE *
cd ..
