#!/bin/bash
VERSION=`grep "_DOTTED_VERSION = '" libxml_xmlwin32version.inc | cut -d\' -f2`
LIBNAME=libxml2
PACKAGE=$LIBNAME-pas
RELEASENAME=$PACKAGE-$VERSION-src
TAG="`echo $LIBNAME\_$VERSION | tr [:lower:] [:upper:] | sed 's/\./_/g'`"
MYTMP=./$TAG.tmp
CVSROOT=:pserver:anonymous@cvs.sourceforge.net:/cvsroot/libxml2-pas

############################################################################
queryExtension() {
	case $TERM in
	cygwin*) EXT=zip ;;
	*) EXT=tgz ;;
	esac
}
############################################################################
queryArchiveFile()
{
	queryExtension
	case "$EXT" in
	zip)
		ARCHIVEFILE=$RELEASENAME.$EXT
		PACKCMD="zip -qr ../$ARCHIVEFILE *"
	;;
	tgz)
		ARCHIVEFILE=$RELEASENAME.$EXT
		PACKCMD="tar -zcf ../$ARCHIVEFILE *"
	;;
	esac
}
############################################################################
createArchive() 
{
	queryArchiveFile
	echo "Extracting $LIBNAME-pas from CVS tag $TAG ..."
	rm -rf $MYTMP
	cvs -z4 -d $CVSROOT export -r $TAG -d $MYTMP .

	echo "Preparing archive $ARCHIVEFILE ..."
	rm -f $ARCHIVEFILE
	cd $MYTMP
	cat libxml2/INFO.txt.template | sed "s:@VERSION@:$VERSION:g" | sed "s:@DATE@:`date +'%d %b %Y'`:g" >INFO.txt
	rm libxml2/INFO.txt.template
	$PACKCMD
	cd ..
}
############################################################################
function uploadToSourceForge()
{
	queryArchiveFile
	echo "Uploading $ARCHIVEFILE to sourceforge.net FTP server (incoming)"
	ftp-put.sh upload.log upload.sourceforge.net incoming $ARCHIVEFILE $ARCHIVEFILE anonymous libxml2-pas@sourceforge.net
	cat upload.log
	rm upload.log
}
############################################################################

CMD=$1
case $CMD in
dist) createArchive ;;
upload) uploadToSourceForge	;;
*) echo "Usage: $0 [dist|upload]" ;;
esac
