#!/bin/bash

VERSION=2.4.13
PACKAGE=libxml2-pas
ARCHIVE=$PACKAGE-$VERSION
TAG=`echo "LIBXML_$VERSION" | sed "s/\./_/g"`

rm $ARCHIVE.tgz
CVSROOT=:pserver:anonymous@cvs.sourceforge.net:/cvsroot/libxml2-pas
echo "Reading files for export from tag '$TAG' ..."
#mkdir tmp
cvs -d $CVSROOT export -l -r HEAD -d tmp .
cvs -d $CVSROOT export -r $TAG -d tmp .

echo "Creating archive $ARCHIVE.tgz"
cd tmp
tar -zcf ../$ARCHIVE.tgz *
cd ..
rm -rf ./tmp

echo "Sending archive $ARCHIVE.tgz to upload.sourceforge.net ..."
ftp-put.sh upload.log upload.sourceforge.net incoming $ARCHIVE.tgz $ARCHIVE.tgz anonymous libxml2-pas@sourceforge.net; cat upload.log; rm upload.log
echo "Done."
